build_root:
  image_stream_tag:
    name: ci-framework-image
    namespace: openstack-k8s-operators
    tag: latest
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: molecule-test
  commands: |
    export HOME=/tmp
    export ANSIBLE_LOCAL_TMP=/tmp
    export ANSIBLE_REMOTE_TMP=/tmp
    make -C ../ci-framework molecule_nodeps ROLE_DIR=../edpm-ansible/edpm_ansible/roles/
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openstack-k8s-operators
  repo: edpm-ansible
